### busca todos
GET http://localhost:8080/produto


### adiciona
POST http://localhost:8080/produto/criar
Content-Type: application/json

{
  "nome": "ana"
}

###

### atualiza um
PUT http://localhost:8080/produto/atualizar
Content-Type: application/json

{
  "id": 1,
  "nome": "joaozin3"
}

###

### remove um
DELETE http://localhost:8080/produto
Content-Type: application/json

{
  "id": 1
}

###